server:
  servlet:
    context-path: /api
  port: 8070

spring:
  application:
    name: seller-system
  datasource:
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:123456}
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/seller_db}
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: userTransactionStatusMessage:com.seller.sellersystem.usertransaction.messages.UserTransactionStatusMessage
    consumer:
      group-id: boughts_group
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: reducePositionAmountMessage:com.seller.sellersystem.position.messages.ReducePositionAmountMessage

  jpa:
    properties:
      hibernate:
        default_schema: seller_system
  profiles:
    active: postgres
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  liquibase:
    change-log: classpath:db/changelog/sellersystem/db.changelog.xml

cache:
  expiration: 1h
  max-size: 20

kafka:
  topics:
    boughts_topic: topic_boughts
    transaction_status_topic: topic_transaction_status