apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  kafka-listener-security-protocol-map: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
  kafka-advertised-listeners: PLAINTEXT://:29092,PLAINTEXT_INTERNAL://kafka-service:9092
  kafka-zookeeper-connect: zookeeper-service:2181
  kafka-broker-id: '1'
  kafka-offsets-topic-replication-factor: '1'
  kafka-url: kafka-service:9092