scrape_configs:
  - job_name: 'seller-system'
    scrape_interval: 2s
    metrics_path: 'api/actuator/prometheus'
    static_configs:
      - targets: ['seller-system:8070']
  - job_name: 'company-service'
    scrape_interval: 2s
    metrics_path: 'api/actuator/prometheus'
    static_configs:
      - targets: ['company-service:8072']
  - job_name: 'user-transaction-service'
    scrape_interval: 2s
    metrics_path: 'api/actuator/prometheus'
    static_configs:
      - targets: ['user-transaction-service:8074']