server:
  servlet:
    context-path: /api
  port: 8072

spring:
  application:
    name: company-service
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411/}
  datasource:
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:123456}
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/seller_db}
  jpa:
    properties:
      hibernate:
        default_schema: companies
  profiles:
    active: postgres
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  liquibase:
    change-log: classpath:db/changelog/companies/db.changelog.xml

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus