server:
  servlet:
    context-path: /api
  port: 8072

spring:
  application:
    name: company-service
  jpa:
    properties:
      hibernate:
        default_schema: companies
  profiles:
    active: postgres-local
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  liquibase:
    change-log: classpath:db/changelog/companies/db.changelog.xml
