server:
  servlet:
    context-path: /api
  port: 8074

spring:
  application:
    name: user-transaction-service
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411/}
  cache:
    cache-names: users
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      username: ${MONGO_DB_USERNAME:sa}
      password: ${MONGO_DB_PASSWORD:123456}
      database: ${MONGO_DB_DATABASE:seller_db}
      authentication-database: admin
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: reducePositionAmountMessage:com.seller.usertransactionservice.usertransaction.messages.ReducePositionAmountMessage
    consumer:
      group-id: user_transaction_status_group
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: userTransactionStatusMessage:com.seller.usertransactionservice.usertransaction.messages.UserTransactionStatusMessage

  jpa:
    properties:
      hibernate:
        default_schema: user_transactions
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

pagination:
  max-page-size: 20

kafka:
  topics:
    boughts_topic: topic_boughts
    transaction_status_topic: topic_transaction_status

redis:
  default:
    expiration: 3m

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - prometheus